{{- /* vim: filetype=go
deployment:
  meta:
  template:
    meta:
  strategy: # default is rolling
  minReadySeconds: # minimum ready seconds
  autoscaling:
    meta:
    minReplicas: 1
    maxReplicas: 100
    targetCPU: 80
    targetMemory: 80

*/}}
{{- with .Values.deployment }}
{{- include "k8s-rocker.object" (list $ "apps/v1" "Deployment" (include "k8s-rocker.name"  $  ) .)
}}
spec:
  {{- with .serviceAccount }}
  serviceAccountName: {{ . }}
  automountServiceAccountToken: true
  {{- end }}
  selector:
    matchLabels:
    {{- include "k8s-rocker.matchLabels" $ | indent 6}}
  minReadySeconds: {{ default 0 .minReadySeconds }}
  strategy:
    type: {{ default "RollingUpdate" .strategy }}
  template:
    {{- $meta:= dict }}
    {{- if .template }}
    {{- $meta = .template.meta }}
    {{- end }}
    {{- include "k8s-rocker.meta" ( list $ nil $meta ) | indent 4 }}
    spec:
      {{- include "k8s-rocker.podspec" $ | indent 6 }}
{{- end }}
